import type { Config } from 'tailwindcss';

export default {
    theme: {
        extend: {
            colors: {
                border: 'var(--border)',
                'border-subtle': 'var(--border-subtle)',
                'border-muted': 'var(--border-muted)',
                'border-strong': 'var(--border-strong)',
                'card-border': 'var(--card-border)',
                background: 'var(--background)',
                'background-muted': 'var(--background-muted)',
                foreground: 'var(--foreground)',
                'foreground-muted': 'var(--foreground-muted)',
                'foreground-subtle': 'var(--foreground-subtle)',
                'foreground-faint': 'var(--foreground-faint)',
                'foreground-disabled': 'var(--foreground-disabled)',
                primary: {
                    DEFAULT: 'var(--primary)',
                    foreground: 'var(--primary-foreground)',
                },
                'primary-soft': 'var(--primary-soft)',
                'primary-border': 'var(--primary-border)',
                'primary-strong': 'var(--primary-strong)',
                card: {
                    DEFAULT: 'var(--card)',
                    foreground: 'var(--card-foreground)',
                },
                neutral: 'var(--neutral)',
                secondary: 'var(--secondary)',
                'secondary-soft': 'var(--secondary-soft)',
                'secondary-muted': 'var(--secondary-muted)',
                'secondary-subtle': 'var(--secondary-subtle)',
                'secondary-hover': 'var(--secondary-hover)',
                'secondary-active': 'var(--secondary-active)',
                'secondary-strong': 'var(--secondary-strong)',
                accent: 'var(--accent)',
                'accent-soft': 'var(--accent-soft)',
                info: 'var(--info)',
                'info-soft': 'var(--info-soft)',
                'info-border': 'var(--info-border)',
                success: 'var(--success)',
                'success-soft': 'var(--success-soft)',
                'success-border': 'var(--success-border)',
                warning: 'var(--warning)',
                'warning-soft': 'var(--warning-soft)',
                'warning-border': 'var(--warning-border)',
                error: 'var(--error)',
                'error-soft': 'var(--error-soft)',
                'error-border': 'var(--error-border)',
                overlay: 'var(--overlay)',
                'focus-ring': 'var(--focus-ring)',
                skeleton: 'var(--skeleton)',
                'pattern-stroke': 'var(--pattern-stroke)',
            },
            borderRadius: {
                lg: 'var(--radius-lg)',
                md: 'var(--radius-md)',
                sm: 'var(--radius-sm)',
            },
        },
    },
} satisfies Omit<Config, 'content'>;
