/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLucideAlertCircle: typeof import('~icons/lucide/alert-circle')['default']
    IconLucideAlignCenter: typeof import('~icons/lucide/align-center')['default']
    IconLucideAlignLeft: typeof import('~icons/lucide/align-left')['default']
    IconLucideAlignRight: typeof import('~icons/lucide/align-right')['default']
    IconLucideBold: typeof import('~icons/lucide/bold')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down')['default']
    IconLucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    IconLucideCode: typeof import('~icons/lucide/code')['default']
    IconLucideCopy: typeof import('~icons/lucide/copy')['default']
    IconLucideEye: typeof import('~icons/lucide/eye')['default']
    IconLucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    IconLucideImage: typeof import('~icons/lucide/image')['default']
    IconLucideItalic: typeof import('~icons/lucide/italic')['default']
    IconLucideList: typeof import('~icons/lucide/list')['default']
    IconLucideListOrdered: typeof import('~icons/lucide/list-ordered')['default']
    IconLucideLockKeyhole: typeof import('~icons/lucide/lock-keyhole')['default']
    IconLucideLogOut: typeof import('~icons/lucide/log-out')['default']
    IconLucideMenu: typeof import('~icons/lucide/menu')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucideMoreHorizontal: typeof import('~icons/lucide/more-horizontal')['default']
    IconLucidePlus: typeof import('~icons/lucide/plus')['default']
    IconLucideQuote: typeof import('~icons/lucide/quote')['default']
    IconLucideRedo: typeof import('~icons/lucide/redo')['default']
    IconLucideRefreshCw: typeof import('~icons/lucide/refresh-cw')['default']
    IconLucideScanLine: typeof import('~icons/lucide/scan-line')['default']
    IconLucideSettings: typeof import('~icons/lucide/settings')['default']
    IconLucideShieldBan: typeof import('~icons/lucide/shield-ban')['default']
    IconLucideShieldCheck: typeof import('~icons/lucide/shield-check')['default']
    IconLucideStrikethrough: typeof import('~icons/lucide/strikethrough')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconLucideUnderline: typeof import('~icons/lucide/underline')['default']
    IconLucideUndo: typeof import('~icons/lucide/undo')['default']
  }
}
